### ISSUE TITLE
Vector.OuterProduct is wrong

### ISSUE THREAD

**Issue by arjamba** [Harold2017/golina#2]
In vector.go, OuterProduct() you should 
`res.Set(i, j, (*v)[i]*(*v1)[j]) `
instead of 
`res.Set(i, j, (*v)[i]*(*v)[j])`.

More scary is that TestVector_OuterProduct() is wrong too. You should expect 
`a := Data{{4, 5}, {8, 10}, {12, 15}} `
and not 
`a := Data{{1, 2}, {2, 4}, {3, 6}}`. 
Appears, that currently expected values are fitted with the wrong implementation...

I like your library and would love to use it, but how to be confident there are no other fitted tests...

**Comment by Harold2017** [comment]
emm...  Sorry, that's really a shame i made such a stupid mistake... it should be v1 and the test is wrong either... 
i made this lib as a toy for reviewing my LA math 3 years ago and i think all computation implementation is quite trivial without further optimization, you may fork it and freely use or revise the codes.
If you wish, any pull request is welcome and appreciated.
Really thanks for your comment!

**Comment by Harold2017** [comment]
> In vector.go, OuterProduct() you should `res.Set(i, j, (*v)[i]*(*v1)[j]) ` instead of `res.Set(i, j, (*v)[i]*(*v)[j])`.
> 
> More scary is that TestVector_OuterProduct() is wrong too. You should expect `a := Data{{4, 5}, {8, 10}, {12, 15}} ` and not `a := Data{{1, 2}, {2, 4}, {3, 6}}`. Appears, that currently expected values are fitted with the wrong implementation...
> 
> I like your library and would love to use it, but how to be confident there are no other fitted tests...

Fixed and thanks a lot for your comment.

**Comment by arjamba** [comment]
Thank you for the fix! I will try to use your code with this library [math32](https://github.com/chewxy/math32), as a replacement for the 64-bit standard implementation. Believe it or not, there is no 32-bit linear algebra package implemented in native go.

**Comment by Harold2017** [comment]
> Thank you for the fix! I will try to use your code with this library [math32](https://github.com/chewxy/math32), as a replacement for the 64-bit standard implementation. Believe it or not, there is no 32-bit linear algebra package implemented in native go.

Sounds great, cheer for you!~
